# Generated by Django 4.1.12 on 2023-10-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketreservation",
            name="from_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_station_r",
                to="trains.station",
            ),
        ),
        migrations.AlterField(
            model_name="ticketreservation",
            name="to_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_station_r",
                to="trains.station",
            ),
        ),
    ]
