# Generated by Django 4.1.12 on 2023-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0002_alter_ticketreservation_from_station_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketreservation",
            name="passenger_sex",
            field=models.CharField(max_length=20),
        ),
    ]
