# Generated by Django 4.1.12 on 2023-10-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0003_alter_ticketreservation_passenger_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketreservation",
            name="passenger_sex",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer Not to Say"),
                ],
                max_length=20,
            ),
        ),
    ]
