# Generated by Django 4.1.12 on 2023-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0005_alter_ticketreservation_passenger_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketreservation",
            name="ticket_status",
            field=models.CharField(max_length=10),
        ),
    ]
